# Enter target code first to reuse variables associated
subdir('arm')

subdir('audio')
subdir('block')
subdir('char')
subdir('core')
subdir('cpu')
subdir('display')
subdir('dma')
subdir('gpio')
subdir('i2c')
subdir('input')
subdir('intc')
subdir('misc')
subdir('net')
subdir('nvme')
subdir('nvram')
subdir('pci')
subdir('pci-bridge')
subdir('pci-host')
subdir('rtc')
subdir('sd')
subdir('sensor')
subdir('spmi')
subdir('ssi')
subdir('timer')
subdir('usb')
subdir('watchdog')
