name: build
on:
  push:
    branches:
  pull_request:

jobs:
  build_linux:
    name: Linux Build
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential libtool ninja-build pkg-config libglib2.0-dev gnutls-bin libjpeg-turbo8-dev libpng-dev libslirp-dev libssh-dev libusb-1.0-0-dev liblzo2-dev libncurses5-dev libpixman-1-dev libsnappy-dev vde2 zstd libgnutls28-dev libgmp10 libgmp3-dev lzfse liblzfse-dev python3-pip nettle-bin nettle-dev meson
      - name: Build
        run: |
          mkdir build
          cd build
          export PATH="$HOME/.local/bin:$PATH"
          PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig ../configure --target-list=aarch64-softmmu --disable-werror
          make -j$(nproc)

  build_macos:
    name: macOS Build
    runs-on: macos-26
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: Install dependencies
        run: |
          brew install libtool meson ninja pkgconf glib gnutls jpeg-turbo libpng libslirp libssh libusb lzo ncurses nettle pixman snappy vde zstd lzfse nettle
      - name: Build
        run: |
          mkdir build && cd build
          LIBTOOL="glibtool" ../configure --target-list=aarch64-softmmu --extra-cflags=-DNCURSES_WIDECHAR=1 --disable-sdl --disable-gtk --enable-cocoa --disable-werror --extra-cflags="-I/opt/homebrew/include" --extra-ldflags="-L/opt/homebrew/lib"
          make -j$(sysctl -n hw.logicalcpu)

  build_macos_x86_64:
    name: macOS Build (Intel)
    runs-on: macos-26-intel
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: Install dependencies
        run: |
          brew install libtool meson ninja pkgconf glib gnutls jpeg-turbo libpng libslirp libssh libusb lzo ncurses nettle pixman snappy vde zstd lzfse nettle
      - name: Build
        run: |
          mkdir build && cd build
          LIBTOOL="glibtool" ../configure --target-list=aarch64-softmmu --extra-cflags=-DNCURSES_WIDECHAR=1 --disable-sdl --disable-gtk --enable-cocoa --disable-werror --extra-cflags="-I/opt/homebrew/include" --extra-ldflags="-L/opt/homebrew/lib"
          make -j$(sysctl -n hw.logicalcpu)
